### ISSUE TITLE
Space in description

### ISSUE THREAD

**Issue by tyler36** [b13/ddev-keycloak#1]
I noticed in the output of `ddev get --list --all`, there seems to be a space at the begining of the description of this addon.
Not sure if it intentional or not, but thought I'd pass on the info anyways.

![image](https://github.com/b13/ddev-keycloak/assets/7234392/3b316b21-f90e-4261-979c-504e5ca949e9)

**Comment by ochorocho** [comment]
Fixed. Thank you. :-)
